// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Configure Firebase for your project using FlutterFire CLI
  // Run: flutterfire configure
  // This will generate the actual configuration below

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_AUTH_DOMAIN',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjYZbwPS-sWpp05v95uALerZytGjcc6OI',
    appId: '1:181824121922:android:0a907a5057680ba32851db',
    messagingSenderId: '181824121922',
    projectId: 'rebuild-mama',
    storageBucket: 'rebuild-mama.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQRJDNjPvW8uP8FMYCK5I-Cp_FBTnz5GQ',
    appId: '1:181824121922:ios:362099c65c688fa82851db',
    messagingSenderId: '181824121922',
    projectId: 'rebuild-mama',
    storageBucket: 'rebuild-mama.firebasestorage.app',
    iosBundleId: 'com.example.postpartumRecoveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQRJDNjPvW8uP8FMYCK5I-Cp_FBTnz5GQ',
    appId: '1:181824121922:ios:362099c65c688fa82851db',
    messagingSenderId: '181824121922',
    projectId: 'rebuild-mama',
    storageBucket: 'rebuild-mama.firebasestorage.app',
    iosBundleId: 'com.example.postpartumRecoveryApp',
  );

}